// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhzzkabazldhlkwxmuld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloenprYWJhemxkaGxrd3htdWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjA1MTIsImV4cCI6MjA2NTAzNjUxMn0.eBVGejc1rsV4V0GS9cKAhF93MAOByAIVbCAORxJbhas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});